apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: hostname
  name: hostname
spec:
  replicas: 3
  selector:
    matchLabels:
      run: hostname
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hostname
    spec:
      containers:
      - image: santoshr1016/lights
        name: hostname
        resources: {}
status: {}
